//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamcastShortcutApp.i18n {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainWindow {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainWindow() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DreamcastShortcutApp.i18n.MainWindow", typeof(MainWindow).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar idioma.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create presets.
        /// </summary>
        public static string CreatePresets {
            get {
                return ResourceManager.GetString("CreatePresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear accesos directos.
        /// </summary>
        public static string CreateShortcuts {
            get {
                return ResourceManager.GetString("CreateShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dispositivo.
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partición:.
        /// </summary>
        public static string DreamshellPartition {
            get {
                return ResourceManager.GetString("DreamshellPartition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dreamshell.
        /// </summary>
        public static string DreamshellTitle {
            get {
                return ResourceManager.GetString("DreamshellTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Versión:.
        /// </summary>
        public static string DreamshellVersion {
            get {
                return ResourceManager.GetString("DreamshellVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falta seleccionar la versión.
        /// </summary>
        public static string DreamshellVersionMessage {
            get {
                return ResourceManager.GetString("DreamshellVersionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carpetas.
        /// </summary>
        public static string FoldersTitle {
            get {
                return ResourceManager.GetString("FoldersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carpeta de juegos:.
        /// </summary>
        public static string GameFolder {
            get {
                return ResourceManager.GetString("GameFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falta seleccionar la carpeta de juegos.
        /// </summary>
        public static string GameFolderMessage {
            get {
                return ResourceManager.GetString("GameFolderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Juego con mas de un disco:.
        /// </summary>
        public static string GameMoreDisks {
            get {
                return ResourceManager.GetString("GameMoreDisks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño de imagen:.
        /// </summary>
        public static string ImageSize {
            get {
                return ResourceManager.GetString("ImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma:.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Maximo de accesos directos:.
        /// </summary>
        public static string MaxShortcuts {
            get {
                return ResourceManager.GetString("MaxShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se aceptan valores negativos en el maximo de accesos directos.
        /// </summary>
        public static string MaxShortcutsMessage {
            get {
                return ResourceManager.GetString("MaxShortcutsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Longitud maxima en nombre:.
        /// </summary>
        public static string MaxSizeName {
            get {
                return ResourceManager.GetString("MaxSizeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se aceptan valores negativos en el maximo del nombre.
        /// </summary>
        public static string MaxSizeNameMessage {
            get {
                return ResourceManager.GetString("MaxSizeNameMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Objeto nulo, cierre y vuelva abrir la aplicación.
        /// </summary>
        public static string ObjectNullMessage {
            get {
                return ResourceManager.GetString("ObjectNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opciones.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sobrescribir preset:.
        /// </summary>
        public static string OverwritePreset {
            get {
                return ResourceManager.GetString("OverwritePreset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La partición de los juegos no puede ser diferente a la partición del dreamshell.
        /// </summary>
        public static string PartitionGamesMessage {
            get {
                return ResourceManager.GetString("PartitionGamesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falta seleccionar la partición.
        /// </summary>
        public static string PartitionMessage {
            get {
                return ResourceManager.GetString("PartitionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presets.
        /// </summary>
        public static string Presets {
            get {
                return ResourceManager.GetString("Presets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accesos directo aleatorios:.
        /// </summary>
        public static string RandomShortcuts {
            get {
                return ResourceManager.GetString("RandomShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar accesos directos:.
        /// </summary>
        public static string RemoveShortcuts {
            get {
                return ResourceManager.GetString("RemoveShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presets guardados.
        /// </summary>
        public static string SavePresetsMessage {
            get {
                return ResourceManager.GetString("SavePresetsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Accesos directos guardados.
        /// </summary>
        public static string SaveShorcutsMessage {
            get {
                return ResourceManager.GetString("SaveShorcutsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acessos directos.
        /// </summary>
        public static string Shortcuts {
            get {
                return ResourceManager.GetString("Shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Origen de datos:.
        /// </summary>
        public static string ShortcutsSource {
            get {
                return ResourceManager.GetString("ShortcutsSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar nombre:.
        /// </summary>
        public static string ShowName {
            get {
                return ResourceManager.GetString("ShowName", resourceCulture);
            }
        }
    }
}
